// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL6FXazOApWyvfjWSCKTNf_4N2wIFdHlA',
    appId: '1:864582805104:web:f802c05f0421cd1089f6b5',
    messagingSenderId: '864582805104',
    projectId: 'contactappbackend-19760',
    authDomain: 'contactappbackend-19760.firebaseapp.com',
    storageBucket: 'contactappbackend-19760.firebasestorage.app',
    measurementId: 'G-059YHPLBN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkWEzbyuPiHN5_iusq3FO4LTCbVigVSDE',
    appId: '1:864582805104:android:bf1d4e0b0d7c753689f6b5',
    messagingSenderId: '864582805104',
    projectId: 'contactappbackend-19760',
    storageBucket: 'contactappbackend-19760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfyE0isIueYHknHSBvKbChBp87T9PDe2U',
    appId: '1:864582805104:ios:2cc84b5f4bc0d26e89f6b5',
    messagingSenderId: '864582805104',
    projectId: 'contactappbackend-19760',
    storageBucket: 'contactappbackend-19760.firebasestorage.app',
    iosBundleId: 'com.example.frebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfyE0isIueYHknHSBvKbChBp87T9PDe2U',
    appId: '1:864582805104:ios:2cc84b5f4bc0d26e89f6b5',
    messagingSenderId: '864582805104',
    projectId: 'contactappbackend-19760',
    storageBucket: 'contactappbackend-19760.firebasestorage.app',
    iosBundleId: 'com.example.frebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL6FXazOApWyvfjWSCKTNf_4N2wIFdHlA',
    appId: '1:864582805104:web:a8b21ae66ea90d4989f6b5',
    messagingSenderId: '864582805104',
    projectId: 'contactappbackend-19760',
    authDomain: 'contactappbackend-19760.firebaseapp.com',
    storageBucket: 'contactappbackend-19760.firebasestorage.app',
    measurementId: 'G-CB8SM4T28F',
  );
}
